services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=threadboard
      - NODE_ENV=development
    command: npm run start:dev

  frontend:
    image: node:18-alpine
    ports:
      - '3001:3001'
    volumes:
      - ./packages/frontend:/app
    working_dir: /app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NODE_ENV=development
      - PORT=3001
    command: sh -c "npm install && npm run dev -- -p 3001"

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=threadboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
